from __future__ import annotations

TRANSCODE_PLAN_SCHEMA_VERSION = 7
NORMALIZED_PROBE_SCHEMA_VERSION = 1
VALIDATION_POLICY_SCHEMA_VERSION = 2
VALIDATION_REPORT_SCHEMA_VERSION = 1
VAPOURSYNTH_PLAN_SCHEMA_VERSION = 1
AV1AN_COMMAND_SCHEMA_VERSION = 4
FFMPEG_MUX_SCHEMA_VERSION = 1
EXECUTION_IDENTITY_SCHEMA_VERSION = 1
AV1AN_STAGE_MARKER_SCHEMA_VERSION = 1
ENCODE_RESULT_RECEIPT_SCHEMA_VERSION = 1

QUEUE_CONTRACT = "queue-job-v1"
WORK_KEY_CONTRACT = "work-v7"
VAPOURSYNTH_TEMPLATE_HASH_CONTRACT = "vpy-template-v1"
VAPOURSYNTH_SCRIPT_HASH_CONTRACT = "vpy-script-v1"
VAPOURSYNTH_IDENTITY_HASH_CONTRACT = "vpy-identity-v1"
EXECUTION_IDENTITY_HASH_CONTRACT = "execution-identity-v1"
PLAN_HASH_CONTRACT = "plan-v4"
PLAN_SEMANTIC_HASH_CONTRACT = "plan-semantic-v1"
PROFILE_HASH_CONTRACT = "profile-v5"
AV1AN_SPEC_HASH_CONTRACT = "av1an-spec-v1"
FFMPEG_MUX_SPEC_HASH_CONTRACT = "ffmpeg-mux-spec-v1"
VALIDATION_POLICY_HASH_CONTRACT = "validation-policy-v2"
PROMOTION_POLICY_HASH_CONTRACT = "promotion-policy-v1"
